/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UiComponentsRouteImport } from './routes/ui-components'
import { Route as ListDemoRouteImport } from './routes/list-demo'
import { Route as FormBuilderV2RouteImport } from './routes/form-builder-v2'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as CvTestRouteImport } from './routes/cv-test'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UiComponentsRoute = UiComponentsRouteImport.update({
  id: '/ui-components',
  path: '/ui-components',
  getParentRoute: () => rootRouteImport,
} as any)
const ListDemoRoute = ListDemoRouteImport.update({
  id: '/list-demo',
  path: '/list-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderV2Route = FormBuilderV2RouteImport.update({
  id: '/form-builder-v2',
  path: '/form-builder-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CvTestRoute = CvTestRouteImport.update({
  id: '/cv-test',
  path: '/cv-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv-test': typeof CvTestRoute
  '/form-builder': typeof FormBuilderRoute
  '/form-builder-v2': typeof FormBuilderV2Route
  '/list-demo': typeof ListDemoRoute
  '/ui-components': typeof UiComponentsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv-test': typeof CvTestRoute
  '/form-builder': typeof FormBuilderRoute
  '/form-builder-v2': typeof FormBuilderV2Route
  '/list-demo': typeof ListDemoRoute
  '/ui-components': typeof UiComponentsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv-test': typeof CvTestRoute
  '/form-builder': typeof FormBuilderRoute
  '/form-builder-v2': typeof FormBuilderV2Route
  '/list-demo': typeof ListDemoRoute
  '/ui-components': typeof UiComponentsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv-test'
    | '/form-builder'
    | '/form-builder-v2'
    | '/list-demo'
    | '/ui-components'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv-test'
    | '/form-builder'
    | '/form-builder-v2'
    | '/list-demo'
    | '/ui-components'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/cv-test'
    | '/form-builder'
    | '/form-builder-v2'
    | '/list-demo'
    | '/ui-components'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvTestRoute: typeof CvTestRoute
  FormBuilderRoute: typeof FormBuilderRoute
  FormBuilderV2Route: typeof FormBuilderV2Route
  ListDemoRoute: typeof ListDemoRoute
  UiComponentsRoute: typeof UiComponentsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-components': {
      id: '/ui-components'
      path: '/ui-components'
      fullPath: '/ui-components'
      preLoaderRoute: typeof UiComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-demo': {
      id: '/list-demo'
      path: '/list-demo'
      fullPath: '/list-demo'
      preLoaderRoute: typeof ListDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder-v2': {
      id: '/form-builder-v2'
      path: '/form-builder-v2'
      fullPath: '/form-builder-v2'
      preLoaderRoute: typeof FormBuilderV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-test': {
      id: '/cv-test'
      path: '/cv-test'
      fullPath: '/cv-test'
      preLoaderRoute: typeof CvTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvTestRoute: CvTestRoute,
  FormBuilderRoute: FormBuilderRoute,
  FormBuilderV2Route: FormBuilderV2Route,
  ListDemoRoute: ListDemoRoute,
  UiComponentsRoute: UiComponentsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
