/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CvTestRouteImport } from './routes/cv-test'
import { Route as IndexRouteImport } from './routes/index'

const CvTestRoute = CvTestRouteImport.update({
  id: '/cv-test',
  path: '/cv-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv-test': typeof CvTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv-test': typeof CvTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv-test': typeof CvTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv-test'
  id: '__root__' | '/' | '/cv-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvTestRoute: typeof CvTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cv-test': {
      id: '/cv-test'
      path: '/cv-test'
      fullPath: '/cv-test'
      preLoaderRoute: typeof CvTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvTestRoute: CvTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
