// rf.types.ts
// TODO: This was generated by ChatGPT. The plan is to implement and check the types as needed when building features.
export type RfConfig = {
   baseUrl: string;                // e.g. http://localhost:9001
   apiKey?: string;                // optional for local
   serviceSecret?: string;         // optional
   defaultTimeoutMs?: number;      // e.g. 20_000
};

export type Box = { x: number; y: number; w: number; h: number };
export type Detection = { class: string; score: number; box: Box };
export type Segment = { class: string; score: number; polygon?: number[]; rleMask?: string };
export type Keypoint = { name?: string; x: number; y: number; score: number };

export type ImageInput = { url?: string; base64?: string }; // send one

export type ODRequest = ImageInput & { confidence?: number; iou?: number };
export type ODResponse = { predictions: Detection[] };

export type ISegRequest = ImageInput & { confidence?: number; iou?: number; mask_decode_mode?: "accurate"|"fast" };
export type ISegResponse = { predictions: Segment[] };

export type ClsRequest = ImageInput;
export type ClsResponse = { predictions: { class: string; score: number }[] };

export type KptsRequest = ImageInput & { confidence?: number; keypoint_confidence?: number };
export type KptsResponse = { predictions: { class: string; score: number; keypoints: Keypoint[] }[] };

export type OcrRequest = ImageInput;
export type OcrResponse = { text: string; blocks?: unknown };

export type DepthRequest = ImageInput;
export type DepthResponse = { depthMap: string /* base64 PNG or path */ };

export type SamEmbedRequest = ImageInput;
export type SamEmbedResponse = { embedding: number[] | string };

export type SamSegRequest = ImageInput & { points?: {x:number;y:number}[]; boxes?: Box[] };
export type SamSegResponse = { masks: { score: number; rle: string }[] };

export type ClipEmbedImageReq = ImageInput;
export type ClipEmbedTextReq = { text: string };
export type ClipEmbedResp = { embedding: number[] };
export type ClipCompareReq = { a: { imageUrl?: string; text?: string }, b: { imageUrl?: string; text?: string } };
export type ClipCompareResp = { score: number };

export type WorkflowRunReq = {
   specification?: object;              // for /workflows/run
   inputs?: Record<string, unknown>;
};
export type WorkflowRunResp = { outputs: Record<string, unknown> };

export type PipelineId = string;
