// Roboflow.client.ts
// TODO: This file was generated by ChatGPT, we will be validating the code as needed while building out features
import {
   ClipCompareReq, ClipCompareResp,
   ClipEmbedImageReq, ClipEmbedResp, ClipEmbedTextReq,
   ClsRequest,
   ClsResponse,
   ISegRequest,
   ISegResponse,
   KptsRequest, KptsResponse, OcrRequest, OcrResponse,
   ODRequest,
   ODResponse, PipelineId,
   RfConfig, SamEmbedRequest, SamEmbedResponse, SamSegRequest, SamSegResponse, WorkflowRunResp,
} from './roboflow.types'

const q = (p: Record<string, any>) =>
   Object.entries(p).filter(([,v]) => v !== undefined && v !== null)
      .map(([k,v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`).join("&");

const dataUri = (b64: string) => b64.startsWith("data:") ? b64 : `data:image/jpeg;base64,${b64}`;

export class RoboflowClient {
   constructor(private cfg: RfConfig) {}

   private async post<T>(path: string, body: any, opts?: { timeoutMs?: number; query?: Record<string, any> }): Promise<T> {
      const { defaultTimeoutMs = 20_000, apiKey, serviceSecret } = this.cfg;
      const ac = new AbortController();
      const t = setTimeout(() => ac.abort(), opts?.timeoutMs ?? defaultTimeoutMs);
      const query = q({ api_key: apiKey, service_secret: serviceSecret, ...(opts?.query ?? {}) });
      const url = `${this.cfg.baseUrl}${path}${query ? `?${query}` : ""}`;
      try {
         const res = await fetch(url, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(body),
            signal: ac.signal,
         });
         if (!res.ok) throw new Error(`RF_HTTP_${res.status}`);
         return await res.json() as T;
      } finally {
         clearTimeout(t);
      }
   }

   private async get<T>(path: string, opts?: { timeoutMs?: number; query?: Record<string, any> }): Promise<T> {
      const { defaultTimeoutMs = 20_000, apiKey, serviceSecret } = this.cfg;
      const ac = new AbortController();
      const t = setTimeout(() => ac.abort(), opts?.timeoutMs ?? defaultTimeoutMs);
      const query = q({ api_key: apiKey, service_secret: serviceSecret, ...(opts?.query ?? {}) });
      const url = `${this.cfg.baseUrl}${path}${query ? `?${query}` : ""}`;
      try {
         const res = await fetch(url, { method: "GET", signal: ac.signal });
         if (!res.ok) throw new Error(`RF_HTTP_${res.status}`);
         return await res.json() as T;
      } finally {
         clearTimeout(t);
      }
   }

   // ---- service/model mgmt
   info() { return this.get<{ name: string; version: string }>("/info"); }
   deviceStats() { return this.get<Record<string, any>>("/device/stats"); }
   metrics() { return this.get<Record<string, any>>("/metrics"); }
   listModels() { return this.get<{ models: Record<string, any> }>("/model/registry"); }
   addModel(model_id: string) { return this.post("/model/add", { model_id }); }
   removeModel(model_id: string) { return this.post("/model/remove", { model_id }); }
   clearModels() { return this.post("/model/clear", {}); }

   // ---- core inference
   detect(req: ODRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<ODResponse>("/infer/object_detection", { model_id: "", image, confidence: req.confidence, iou: req.iou });
   }
   segment(req: ISegRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<ISegResponse>("/infer/instance_segmentation", { model_id: "", image, confidence: req.confidence, iou: req.iou, mask_decode_mode: req.mask_decode_mode });
   }
   classify(req: ClsRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<ClsResponse>("/infer/classification", { model_id: "", image });
   }
   keypoints(req: KptsRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<KptsResponse>("/infer/keypoints_detection", { model_id: "", image, keypoint_confidence: req.keypoint_confidence, confidence: req.confidence });
   }

   // ---- OCR
   doctr(req: OcrRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<OcrResponse>("/doctr/ocr", { image });
   }
   trocr(req: OcrRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<OcrResponse>("/ocr/trocr", { image });
   }

   // ---- SAM
   samEmbed(req: SamEmbedRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<SamEmbedResponse>("/sam/embed_image", { image });
   }
   samSegment(req: SamSegRequest) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<SamSegResponse>("/sam/segment_image", { image, points: req.points, boxes: req.boxes });
   }

   // ---- CLIP
   clipEmbedImage(req: ClipEmbedImageReq) {
      const image = req.url ?? dataUri(String(req.base64));
      return this.post<ClipEmbedResp>("/clip/embed_image", { image });
   }
   clipEmbedText(req: ClipEmbedTextReq) {
      return this.post<ClipEmbedResp>("/clip/embed_text", { text: req.text });
   }
   clipCompare(req: ClipCompareReq) {
      return this.post<ClipCompareResp>("/clip/compare", req);
   }

   // ---- workflows
   runWorkflowById(workspace: string, workflowId: string, inputs: Record<string, unknown> = {}) {
      return this.post<WorkflowRunResp>(`/${workspace}/workflows/${workflowId}`, { inputs });
   }
   runWorkflowSpec(specification: object, inputs: Record<string, unknown> = {}) {
      return this.post<WorkflowRunResp>("/workflows/run", { specification, inputs });
   }

   // ---- pipelines (video)
   listPipelines() { return this.get<{ pipelines: any[] }>("/inference_pipelines/list"); }
   pipelineStatus(id: PipelineId) { return this.get(`/inference_pipelines/${id}/status`); }
   initPipeline(payload: Record<string, unknown>) { return this.post("/inference_pipelines/initialise", payload); }
   pausePipeline(id: PipelineId) { return this.post(`/inference_pipelines/${id}/pause`, {}); }
   resumePipeline(id: PipelineId) { return this.post(`/inference_pipelines/${id}/resume`, {}); }
   terminatePipeline(id: PipelineId) { return this.post(`/inference_pipelines/${id}/terminate`, {}); }
   consumePipeline(id: PipelineId) { return this.get(`/inference_pipelines/${id}/consume`); }
}
